#include "utils/utils.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "pico/rand.h"
#include "pico/stdlib.h"

#include "data_structures/string_list.h"

collector *collector_inst;

void collector_init() {
  collector_inst = (collector *)malloc(sizeof(collector));
  collector_inst->count = 0;
  for (uint8_t i = 0; i < COLLECTOR_MAX_STR; i++) {
    collector_inst->pointers[i] = NULL;
  }
}

void collector_add(char *str) {
  if (collector_inst->count >= COLLECTOR_MAX_STR) {
    printf("!!! Collector is full !!!\n");
    return;
  }
  collector_inst->pointers[collector_inst->count] = str;
  collector_inst->count++;
}

/**
 * @brief Frees all strings that were generated by string_add()
 * this is to make possible the nested usage of string_add() without
 * keeping pointers
 */
void collect() {
  for (uint8_t i = 0; i < collector_inst->count; i++) {
    if (collector_inst->pointers[i] != NULL) {
      free(collector_inst->pointers[i]);
      collector_inst->pointers[i] = NULL;
    }
  }
  collector_inst->count = 0;
}

/**
 * @brief Concatenates two strings.
 * It is not necessary to keep the returned pointer to later free it as it is
 * automatically added to the collector, you can call collect() to free
 * all the strings that were generated by string_add().
 * This allows for nested and clean usage of string_add().
 *
 * @param str1 The first string.
 * @param str2 The second string.
 * @return A new string that is the concatenation of str1 and str2, or NULL on
 * failure.
 */
char *string_add(char *str1, char *str2) {
  size_t len1 = strlen(str1);
  size_t len2 = strlen(str2);
  char *result = malloc(len1 + len2 + 1);
  if (!result)
    return NULL;
  for (size_t i = 0; i < len1; ++i)
    result[i] = str1[i];
  for (size_t i = 0; i < len2; ++i)
    result[len1 + i] = str2[i];
  result[len1 + len2] = '\0';
  collector_add(result);
  return result;
}

uint16_t array_find_max(uint16_t *array, size_t len) {
  uint16_t max = 0;
  for (uint8_t i = 0; i < len; i++)
    if (array[i] > max)
      max = array[i];
  return max;
}

uint16_t array_find_min(uint16_t *array, size_t len) {
  uint16_t min = array[0];
  for (uint8_t i = 0; i < len; i++)
    if (array[i] < min)
      min = array[i];
  return min;
}

bool is_string_numeric(char *str) {
  for (uint8_t i = 0; i < strlen(str); i++)
    if (str[i] < '0' || str[i] > '9')
      return false;
  return true;
}

bool is_string_alphanumeric(char *str) {
  for (uint8_t i = 0; i < strlen(str); i++)
    if ((str[i] < '0' || str[i] > '9') && (str[i] < 'A' || str[i] > 'Z') &&
        (str[i] < 'a' || str[i] > 'z'))
      return false;
  return true;
}

bool is_string_alpha(char *str) {
  for (uint8_t i = 0; i < strlen(str); i++)
    if ((str[i] < 'A' || str[i] > 'Z') && (str[i] < 'a' || str[i] > 'z'))
      return false;
  return true;
}

void wait_for_user_input() {
  while (!stdio_usb_connected()) {
    sleep_ms(100);
  }
  printf("Watchdog_2040 tester, send any key to continue...\n");
  while (1) {
    getchar();
    break;
  }
}

str_list *string_split(char *str, char delimiter) {
  str_list *result = list_init();
  char *copy = strdup(str);
  char delim[2] = {delimiter, '\0'};
  char *token = strtok(copy, delim);
  while (token != NULL) {
    list_append(result, strdup(token));
    token = strtok(NULL, delim);
  }
  free(copy);
  return result;
}

char *string_remove_linefeed(char *str) {
  char *newstr = strdup(str);
  size_t len = strlen(newstr);
  if (len > 0 && newstr[len - 1] == '\n')
    newstr[len - 1] = '\0';
  return newstr;
}

char *string_replace(char *str, char old_char, char new_char) {
  char *newstr = strdup(str);
  for (size_t i = 0; i < strlen(newstr); i++)
    if (newstr[i] == old_char)
      newstr[i] = new_char;
  return newstr;
}

char *gen_random_string(size_t length) {
  char *s = malloc(length + 1);
  for (uint8_t i = 0; i < length; i++) {
    s[i] = 'A' + get_rand_32() % 26;
  }
  s[length] = '\0';
  return s;
}

char *
string_substring_replace(const char *str, const char *old, const char *new) {
  size_t str_len = strlen(str);
  size_t old_len = strlen(old);
  size_t new_len = strlen(new);
  if (old_len == 0)
    return NULL;
  size_t count = 0;
  const char *p = str;
  while ((p = strstr(p, old)) != NULL) {
    count++;
    p += old_len;
  }
  size_t new_str_len = str_len + count * (new_len - old_len) + 1;
  char *result = malloc(new_str_len);
  if (!result)
    return NULL;
  char *dst = result;
  p = str;
  const char *match;
  while ((match = strstr(p, old)) != NULL) {
    size_t bytes_before = match - p;
    memcpy(dst, p, bytes_before);
    dst += bytes_before;
    memcpy(dst, new, new_len);
    dst += new_len;
    p = match + old_len;
  }
  strcpy(dst, p);
  return result;
}
